#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <qty_test_icons.h>

int32_t qty_test_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm qty_test!");

    return 0;
}
