#include "qrencode/qrcodegen.h"
#include <furi.h>
#include <gui/gui.h>
#include <gui/elements.h>
#include <gui/modules/text_input.h>
#include "qrcode_renderer.h"

#define MAX_TEXT_LEN 100
#define INPUT_BUFFER_SIZE 32

/* generated by fbt from .png files in images folder */
#include <qrcode_generator_icons.h>

static void generate_and_print_qrcode(Canvas* canvas, const char* text) {
	enum qrcodegen_Ecc errCorLvl = qrcodegen_Ecc_LOW;

	// Make and print the QR Code symbol
	uint8_t qrcode[qrcodegen_BUFFER_LEN_MAX];
	uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
	qrcodegen_encodeText(text, tempBuffer, qrcode, errCorLvl,
			qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);

    render_qrcode(canvas, qrcode);
}

void draw_callback (Canvas* const canvas,  void* ctx) {
    furi_assert(canvas);
    furi_assert(ctx);

	const char* text = "Hello, world!";
    generate_and_print_qrcode(canvas, text);
}

int32_t qrcode_generator_app(void* p) {
	UNUSED(p);

	Gui* gui = furi_record_open("gui");
	ViewPort* view_port = view_port_alloc();
	
    view_port_draw_callback_set(view_port, draw_callback, NULL);

    gui_add_view_port(gui, view_port, GuiLayerFullscreen);
    view_port_update(view_port);

    furi_delay_ms(5000);

	gui_remove_view_port(gui, view_port);
	view_port_free(view_port);
	furi_record_close("gui");
	
    return 0;
}
